# Generated by Django 5.1 on 2024-09-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank=True, default='products/img_not_found.webp', null=True, upload_to='products/'),
        ),
    ]
